# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1507/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1507/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/razvan/Documents/NetworkDevicesManager/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/razvan/Documents/NetworkDevicesManager

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1507/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1507/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/razvan/Documents/NetworkDevicesManager/CMakeFiles /home/razvan/Documents/NetworkDevicesManager//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/razvan/Documents/NetworkDevicesManager/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tcp_server

# Build rule for target.
tcp_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tcp_server
.PHONY : tcp_server

# fast build rule for target.
tcp_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/build
.PHONY : tcp_server/fast

#=============================================================================
# Target rules for targets named tcp_client

# Build rule for target.
tcp_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tcp_client
.PHONY : tcp_client

# fast build rule for target.
tcp_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/build
.PHONY : tcp_client/fast

SQLite_manager.o: SQLite_manager.cpp.o
.PHONY : SQLite_manager.o

# target to build an object file
SQLite_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/SQLite_manager.cpp.o
.PHONY : SQLite_manager.cpp.o

SQLite_manager.i: SQLite_manager.cpp.i
.PHONY : SQLite_manager.i

# target to preprocess a source file
SQLite_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/SQLite_manager.cpp.i
.PHONY : SQLite_manager.cpp.i

SQLite_manager.s: SQLite_manager.cpp.s
.PHONY : SQLite_manager.s

# target to generate assembly for a file
SQLite_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/SQLite_manager.cpp.s
.PHONY : SQLite_manager.cpp.s

tcp_client.o: tcp_client.cpp.o
.PHONY : tcp_client.o

# target to build an object file
tcp_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/tcp_client.cpp.o
.PHONY : tcp_client.cpp.o

tcp_client.i: tcp_client.cpp.i
.PHONY : tcp_client.i

# target to preprocess a source file
tcp_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/tcp_client.cpp.i
.PHONY : tcp_client.cpp.i

tcp_client.s: tcp_client.cpp.s
.PHONY : tcp_client.s

# target to generate assembly for a file
tcp_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/tcp_client.cpp.s
.PHONY : tcp_client.cpp.s

tcp_client_func.o: tcp_client_func.cpp.o
.PHONY : tcp_client_func.o

# target to build an object file
tcp_client_func.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/tcp_client_func.cpp.o
.PHONY : tcp_client_func.cpp.o

tcp_client_func.i: tcp_client_func.cpp.i
.PHONY : tcp_client_func.i

# target to preprocess a source file
tcp_client_func.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/tcp_client_func.cpp.i
.PHONY : tcp_client_func.cpp.i

tcp_client_func.s: tcp_client_func.cpp.s
.PHONY : tcp_client_func.s

# target to generate assembly for a file
tcp_client_func.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/tcp_client_func.cpp.s
.PHONY : tcp_client_func.cpp.s

tcp_server.o: tcp_server.cpp.o
.PHONY : tcp_server.o

# target to build an object file
tcp_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/tcp_server.cpp.o
.PHONY : tcp_server.cpp.o

tcp_server.i: tcp_server.cpp.i
.PHONY : tcp_server.i

# target to preprocess a source file
tcp_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/tcp_server.cpp.i
.PHONY : tcp_server.cpp.i

tcp_server.s: tcp_server.cpp.s
.PHONY : tcp_server.s

# target to generate assembly for a file
tcp_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/tcp_server.cpp.s
.PHONY : tcp_server.cpp.s

tcp_server_func.o: tcp_server_func.cpp.o
.PHONY : tcp_server_func.o

# target to build an object file
tcp_server_func.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/tcp_server_func.cpp.o
.PHONY : tcp_server_func.cpp.o

tcp_server_func.i: tcp_server_func.cpp.i
.PHONY : tcp_server_func.i

# target to preprocess a source file
tcp_server_func.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/tcp_server_func.cpp.i
.PHONY : tcp_server_func.cpp.i

tcp_server_func.s: tcp_server_func.cpp.s
.PHONY : tcp_server_func.s

# target to generate assembly for a file
tcp_server_func.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/tcp_server_func.cpp.s
.PHONY : tcp_server_func.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tcp_client"
	@echo "... tcp_server"
	@echo "... SQLite_manager.o"
	@echo "... SQLite_manager.i"
	@echo "... SQLite_manager.s"
	@echo "... tcp_client.o"
	@echo "... tcp_client.i"
	@echo "... tcp_client.s"
	@echo "... tcp_client_func.o"
	@echo "... tcp_client_func.i"
	@echo "... tcp_client_func.s"
	@echo "... tcp_server.o"
	@echo "... tcp_server.i"
	@echo "... tcp_server.s"
	@echo "... tcp_server_func.o"
	@echo "... tcp_server_func.i"
	@echo "... tcp_server_func.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

