FROM ubuntu:24.04

RUN apt-get update && apt-get install -y rsyslog cron && rm -rf /var/lib/apt/lists/*

RUN sed -i '/imklog/s/^/

RUN echo "*.* @monitor-server:514" >> /etc/rsyslog.conf

CMD service rsyslog start && cron -f